shorturl/urls.py
from django.conf.urls.defaults import patterns, include, url
import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'shorturl.views.home', name='home'),
    url(r'^$', 'shorturl.views.home'),
    url(r'page/about/$', 'shorturl.views.about'),
    url(r'page/contact/$', 'shorturl.views.contact'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    
    url(r'^(?P<short>.+)/$', 'shorturl.views.short_url_redirect'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += patterns('',
)

shorturl/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
class Sue(models.Model):
  original = models.CharField(max_length=8192)
  owner = models.ForeignKey(User, null=True, blank=True, related_name="%(app_label)s_%(class)s_related_"+"owner")
  created_date = models.DateTimeField(null=True,blank=True, auto_now_add=True)
  count = models.PositiveSmallIntegerField(null=True,blank=True)
  def __unicode__(self):  
    return self.short
  class Meta:
    ordering = ['original']

shorturl/forms.py
from django.forms import ModelForm
from django import forms
from django.forms import fields, models, formsets, widgets
from shorturl.models import Sue

class SueForm(models.ModelForm):
    
    class Meta:
        model = Sue

        exclude = ('short','owner', 'count', 'created_date')

shorturl/views.py
from django.shortcuts import render_to_response ,redirect
from shorturl.forms import SueForm
from shorturl.models import Sue
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
import short_url_algorithm
from django.core.exceptions import ObjectDoesNotExist
import sys
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
import settings
import datetime
val = URLValidator(verify_exists=False)
def short_url_redirect(request,short):
    try:
        s_id = short_url_algorithm.decode_url(short)        
         
        sue = Sue.objects.get(id= s_id)
        original = sue.original
        sue.count = sue.count + 1
        sue.save()
        return redirect(original)
    except ObjectDoesNotExist,e :
        original = 'http://u.zzn.im' 
        return render_to_response('redirect.html', {
            'url':original
        },RequestContext(request))  
    except ValueError,e :
        original = 'http://u.zzn.im' 
 
        return render_to_response('redirect.html', {
            'url':original
        },RequestContext(request))  
     
def home(request):
    stored = Sue.objects.all()
    for s in stored:
      s.short = short_url_algorithm.encode_url(s.id)

    if request.method == 'POST': # If the form has been submitted...
        sue_form = SueForm(request.POST) # A form bound to the POST data
        
        if sue_form.is_valid():
            sue = sue_form.save(commit=False)
            sue.count=0;
            sue.created_date=datetime.datetime.now()
            print "xxx"
            o = sue.original
            o_lower = o.lower()
            if o_lower.startswith('http://') ==False and o_lower.startswith('https://') == False:
                sue.original = 'http://'+sue.original
            try:
                val(sue.original)
            except ValidationError, e:
                #TODO-victor: redirect with a error message
                return HttpResponseRedirect('/')
            try:
                # Check if we already have it
                sue = Sue.objects.get(original = sue.original)
            except :
                # Here we insert a new entry
                sue.save()
                return HttpResponseRedirect('/') # Redirect after POST
            return HttpResponseRedirect('/') # Redirect after POST
 
    else:
        sue_form = SueForm() # An unbound form
        
    return render_to_response('index.html', {
        'sue_form': sue_form,
        'stored': stored,
        'current_path': request.get_full_path(),
        'myurl': settings.PROJECT_DOMAIN,
    },RequestContext(request)) 

def contact(request):
    return HttpResponseRedirect('http://www.zzn.im')   
def about(request):
    return render_to_response('about.html', {},RequestContext(request))   

shorturl/templates/about.html
{% extends 'base.html' %}
{% block content %}
<div class="hero-unit span8">
Short URL service is an Open-Source project created by <a href="www.zzn.im">Zainan Victor Zhou</a>
Source code can be found on <a href="https://github.com/xinbenlv/shorturl">Github</a>
</div>
{% endblock %}

shorturl/templates/base.html
<!doctype html>
<html>
<head>

  {% block tittle %} {% endblock%}
    <!-- Le styles -->
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">
  {% block additional_meta %} {% endblock %}
  {% load i18n %}
</head>
<body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Short URL Service</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="/page/about">About</a></li>
              <li><a href="/page/contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row center">
          
            <!--Body content-->
            {% block content %} {% endblock %}
            <!--End of body content-->
        </div>
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script src="http://twitter.github.com/bootstrap/assets/js/bootstrap.js"></script>


</body>
<footer>
<div class="container center">
<a rel="license" href="http://creativecommons.org/licenses/by/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Short URL</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://u.zzn.im" property="cc:attributionName" rel="cc:attributionURL">Zainan Victor Zhou</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 Unported License</a>.<br />Permissions beyond the scope of this license may be available at <a xmlns:cc="http://creativecommons.org/ns#" href="http://u.zzn.im/page/about" rel="cc:morePermissions">http://u.zzn.im/page/about</a>.
</div>
</footer>
</html>

shorturl/templates/index.html

{% extends 'base.html' %}
{% block current_page_subtitle %}Short URL Service{% endblock %}
{% block content %}
<div class="hero-unit span8" >
    Please put your long URL here:
    <form action="/" method="post">
    
    {% csrf_token %}
    <div class="row">
        <div class="span6"><input type="textarea" name="original" class="span6" id="id_original" /></div>
        <div class="span2"><button type="submit" class="btn btn-primary span2" >Shorten</button></div>
    </div>
    </form>
</div>



<div class="span8">
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
            <th>Short</th>
            <th>Oringal</th>
            <th>Count</th>
            <th>Created</th>
            </tr>
        </thead>

        <tbody>
            {% for s in stored%}
            <tr>
                <td><a href="{{s.short}}">{{myurl}}/{{s.short}}</a></td>
                <td>{{s.original}}</td>
                <td>{{s.count}}</td>
                <td>{{s.created_date}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

shorturl/templates/redirect.html
{% extends 'base.html' %}
{% block additional_meta %}
<META HTTP-EQUIV=Refresh CONTENT="3; URL={{url}}">
You're leaving our-website and is going to {{url}} in 3 seconds.
Good luck!
{% endblock %}